version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: jugnu670
      MYSQL_DATABASE: jugnu
      MYSQL_USER: jugnu
      MYSQL_PASSWORD: jugnu670
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  mongodb:
    image: mongo 
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE= db
    ports:
      - "27017:27017"
    volumes:
      - mymongo-data:/data/db
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: jugnu670
      POSTGRES_DB: jugnu
      POSTGRES_USER: jugnu
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis_db
    ports:
      - "6379:6379"
  web :
    depends_on: 
      - mysql
      - mongodb
      - postgres
      - redis
    links:
      - mysql:mysql
      - mongodb:mongodb
      - postgres:postgres
      - redis:redis
    build : .
    restart: always
    ports :
      - "80:80"
      - "81:81"
      - "82:82"
      - "83:83"

  

volumes:
  mysql_data:
  postgres_data:
  mymongo-data: