version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: jugnu670
      POSTGRES_DB: jugnu
      POSTGRES_USER: jugnu
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis_db
    ports:
      - "6379:6379"
  web :
    depends_on: 
      - postgres
      - redis
    links:
      - postgres:postgres
    build : .
    restart: always
    ports :
      - "80:80"
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: jugnu@gmail.com
      PGADMIN_DEFAULT_PASSWORD: jugnu670
    ports:
      - "5050:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:


