version: '3'
services:
  mongodb:
    image: mongo 
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=your-database-name
    volumes:
      - mymongo-data:/data/db

  web :
    depends_on: 
      - mongodb
    links:
      - mongodb:mongodb
    build : .
    restart: always
    ports :
      - "80:80"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  mymongo-data:
    driver: local



